#actief voor alle profiles:
#logging:
#  level:
#    tacos: DEBUG
#
#spring:
#  datasource:
#    schema:
#      - order-schema.sql
#      - ingredient-schema.sql
#      - taco-schema.sql
#      - user-schema.sql
#    data:
#      - ingredients.sql
#    url: jdbc:mysql://localhost/tacocloud
#    username: tacodb
#    password: tacopassword
#    jndi-name: java:/comp/env/jdbc/tacoCloudDS
#
#---
##alles onder de --- is alleen specifiek voor deze profile
#spring:
#  profiles: prod
#  datasource:
#    url: jdbc:mysql://localhost/tacocloud
#    username: tacodb
#    password: tacopassword
#logging:
#  level:
#    tacos: WARN